# Generated by Django 5.0.4 on 2024-04-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(blank=True, max_length=100, null=True)),
                ('product_price', models.CharField(blank=True, max_length=500, null=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='item/')),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
